# Generated by Django 3.2.6 on 2025-03-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HistoriaClinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HistoriaClinica.historiaclinica')),
                ('tipo', models.TextField()),
                ('fecha', models.DateField()),
                ('resultados', models.TextField()),
                ('interpretacion', models.TextField()),
                ('estado', models.TextField()),
                ('ubicacionNodo', models.TextField()),
            ],
        ),
    ]
