# Generated by Django 3.2.6 on 2025-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentesMedicos', models.TextField()),
                ('medicamentosActuales', models.TextField()),
                ('alergias', models.TextField()),
                ('cirugiasPrevias', models.TextField()),
                ('notasAdicionales', models.TextField()),
            ],
        ),
    ]
