# Generated by Django 3.2.6 on 2025-03-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HistoriaClinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.TextField()),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('responsable', models.TextField()),
                ('estado', models.TextField()),
                ('historiaClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.historiaclinica')),
            ],
        ),
    ]
